spring:
  application:
    name: lanchonete
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3307/lanchonete
#    url: jdbc:mysql://mysql_db:3306/lanchonete
    username: user
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
